name: rameshpspkon
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: system-info
        run: |
          echo "fristline"
          date
          hostname
          free -m
          df -h
