name: test-work
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "new one"
      - run: hostname
      - run: date
      - run: free -h
      - run: df -h 
    
